services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lendermatch
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./LenderMatch.API
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=lendermatch;Username=postgres;Password=password
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata: