// <auto-generated />
using System;
using System.Collections.Generic;
using LenderMatch.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LenderMatch.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131221456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LenderMatch.API.Entities.Borrower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualRevenue")
                        .HasColumnType("numeric");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("YearsInBusiness")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Borrowers");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.BusinessCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasComparableDebt")
                        .HasColumnType("boolean");

                    b.Property<int?>("PayNetScore")
                        .HasColumnType("integer");

                    b.Property<int>("TradeLineCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CreditProfiles");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.Lender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("RestrictedIndustries")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("RestrictedStates")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Lenders");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.LendingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ExcludeTrucking")
                        .HasColumnType("boolean");

                    b.Property<int>("LenderId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("MaxEquipmentAgeYears")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("MinFico")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPayNet")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinRevenue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinTimeInBusinessYears")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LenderId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("integer");

                    b.Property<int>("BusinessCreditId")
                        .HasColumnType("integer");

                    b.Property<int>("GuarantorId")
                        .HasColumnType("integer");

                    b.Property<int>("LoanRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId")
                        .IsUnique();

                    b.HasIndex("BusinessCreditId")
                        .IsUnique();

                    b.HasIndex("GuarantorId")
                        .IsUnique();

                    b.HasIndex("LoanRequestId")
                        .IsUnique();

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.LoanRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("EquipmentMileage")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipmentYear")
                        .HasColumnType("integer");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LoanRequests");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.PersonalGuarantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankruptcyDischargeYears")
                        .HasColumnType("integer");

                    b.Property<int>("FicoScore")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBankruptcy")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTaxLiens")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guarantors");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.LendingProgram", b =>
                {
                    b.HasOne("LenderMatch.API.Entities.Lender", "Lender")
                        .WithMany("Programs")
                        .HasForeignKey("LenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lender");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.LoanApplication", b =>
                {
                    b.HasOne("LenderMatch.API.Entities.Borrower", "Business")
                        .WithOne()
                        .HasForeignKey("LenderMatch.API.Entities.LoanApplication", "BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LenderMatch.API.Entities.BusinessCredit", "CreditProfile")
                        .WithOne()
                        .HasForeignKey("LenderMatch.API.Entities.LoanApplication", "BusinessCreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LenderMatch.API.Entities.PersonalGuarantor", "Guarantor")
                        .WithOne()
                        .HasForeignKey("LenderMatch.API.Entities.LoanApplication", "GuarantorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LenderMatch.API.Entities.LoanRequest", "Request")
                        .WithOne()
                        .HasForeignKey("LenderMatch.API.Entities.LoanApplication", "LoanRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("CreditProfile");

                    b.Navigation("Guarantor");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("LenderMatch.API.Entities.Lender", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
